In [5]:
list = [1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [2]:
import numpy as np

In [4]:
arr = np.array(list)
arr

array([1, 2, 3, 4, 5])

In [6]:
my_matrices= [[1,2,3],[4,5,6],[7,8,9]]
my_matrices

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrices)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [11]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [20]:
np.eye(5) #this is the identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(5,5)

array([[0.78509513, 0.13480479, 0.59586913, 0.31404916, 0.85439597],
       [0.46222783, 0.72262099, 0.36559501, 0.8955587 , 0.00264535],
       [0.66224888, 0.95200929, 0.65247968, 0.16234909, 0.54014294],
       [0.35562719, 0.24511412, 0.90832111, 0.90978738, 0.02593085],
       [0.57249943, 0.13529595, 0.61291866, 0.34147366, 0.06142649]])

In [28]:
np.random.randn(8)

array([ 0.43476842,  0.84971973, -0.87107678,  1.34858279,  1.30256473,
        1.55073743,  1.66910838,  0.719809  ])

In [29]:
np.random.randn(4,4)

array([[ 1.68503988,  0.01332751,  0.34091736,  0.43595317],
       [-1.97411416,  0.52479174,  0.34776191, -0.02472214],
       [-2.52123498,  0.9060305 ,  1.67064296, -0.41758037],
       [-2.21932014, -0.56685173,  0.53728915,  0.97765733]])

In [34]:
np.random.randint(1,50,5) # if we want 5 random numbers in between 1 to 50

array([18, 23, 20, 33, 41])

In [42]:
range_arr = np.arange(1,31)
range_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [43]:
range_arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [44]:
range_arr.max()

30

In [45]:
range_arr.min()

1

In [46]:
range_arr.argmax() #find the index of maximum value

29

In [47]:
range_arr.argmin() #find the index of minimum value

0

In [49]:
range_arr.dtype

dtype('int64')

In [50]:
range_arr.shape

(30,)